name: MineZ
version: Development Build 007
website: http://dyrtcraft.pl/
author: TheMolkaPL
description: Plugin stworzony specjalnie dla DyrtCraft Network!

main: pl.themolka.minez.MineZ

commands:
    minez:
        description: MineZ
        aliases: [mz]
        usage: /minez <pomoc|spawn>